apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: adservice
          image: marypearl/adservice:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: default
spec:
  selector:
    app: adservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
