apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: adservice
          image: docker.io/marypearl/adservice:latest  # You can replace 'latest' with a Git SHA if pinned versioning
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"
          readinessProbe:
            grpc:
              port: 9555
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            grpc:
              port: 9555
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  selector:
    app: adservice
  ports:
    - protocol: TCP
      port: 9555
      targetPort: 9555
  type: ClusterIP
